;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Attack.Heavy",DevComment="")
+GameplayTagList=(Tag="Attack.Light.1",DevComment="")
+GameplayTagList=(Tag="Attack.Light.2",DevComment="")
+GameplayTagList=(Tag="Attack.Light.3",DevComment="")
+GameplayTagList=(Tag="Attack.Light.Heavy",DevComment="")
+GameplayTagList=(Tag="Attack.Special1",DevComment="")
+GameplayTagList=(Tag="Attack.Special1.1",DevComment="")
+GameplayTagList=(Tag="Attack.Special1.2",DevComment="")
+GameplayTagList=(Tag="Attack.Special2.1",DevComment="")
+GameplayTagList=(Tag="Attack.Special2.2",DevComment="")
+GameplayTagList=(Tag="Attack.Ultimate",DevComment="")
+GameplayTagList=(Tag="Input.Heavy",DevComment="")
+GameplayTagList=(Tag="Input.Light",DevComment="")
+GameplayTagList=(Tag="Input.Special1",DevComment="")
+GameplayTagList=(Tag="Input.Special2",DevComment="")
+GameplayTagList=(Tag="Input.Ultimate",DevComment="")
+GameplayTagList=(Tag="Team.Enemy",DevComment="")
+GameplayTagList=(Tag="Team.Player",DevComment="")

